apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-sentinel
data:
  redis.conf: |
    # Redis configuration untuk Sentinel setup
    bind 0.0.0.0
    port 6379
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Replication
    replica-announce-ip __POD_IP__
    replica-announce-port 6379
    
    # Performance
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Logging
    loglevel notice
    
    # Security
    protected-mode no
    
    # Timeouts
    timeout 300
    tcp-keepalive 60
